export const TestsArray = [
    "Antenatal Profile",
    "ABO & Rh Blood",
    "ACTH (Adrenocorticotropic Hormone), Blood",
    "Acute Hepatitis Profile (Hep A IgM, Hep B Core Ab, HbSAg and HbSAb)",
    "Alanine Transferase (ALT)",
    "Albumin, CSF",
    "Albumin, Serum",
    "Alkaline Phosphatase (ALP), Serum",
    "Alkaline Phosphatase -Bone Specific",
    "Alpha 1 Antitrypsin",
    "Alpha-Fetoprotein [AFP], Serum",
    "Aspartate Transferase (AST)",
    "Autoimmune Screen (Includes CRP, FBC+ESR, Rf, ANF, ENA Screen)",
    "Blood Group Crossmatch",
    "Blood, Urine",
    "Bone Marrow Aspirate & Treph Reporting",
    "Bone Marrow Aspriation & Biopsy",
    "Breast Cancer Gene 1 (BRCA-1) Mutation",
    "Breast Cancer Gene 2 (BRCA-2) Mutation",
    "Brucella Agglutination Test",
    "BUN (Urea and Creatine) Serum",
    "C-Reactive Protein, Serum",
    "C-Reactive Protein, Ultra Sensitive",
    "Carcino-Embryonic Antigen [CEA]",
    "Cardiac Troponin I",
    "Cardiac Troponin T",
    "Cardiolipin Ab [IgG, IgM, IgA]",
    "Chemotherapy Profile",
    "Chloride, Serum",
    "Cholesterol Total, Serum",
    "Fasting Blood Sugar",
    "Cold Agglutinin Titre",
    "Complete Blood Count (CBC)",
    "Coombs Test Direct",
    "Coombs Test Indirect or Anti- Human Globulin Test",
    "Creatinine, Serum",
    "Creatinine, Urine",
    "Cryptococcal Antigen (CRAG), Serum",
    "Cryptococcal Antigen (CRAG)- CSF",
    "CSF  Cryptococcus India Ink",
    "Gram Stain",
    "CSF IgG Index Profile With Electrophoresis, CSF & Serum",
    "Cystic Fibrosis Extended Screen",
    "Cytomegalovirus (CMV) Antibody IgM, Serum",
    "Erythrocyte Sedimentation Rate (ESR)",
    "Glucose 6-Phosphate Dehydrogenase (G6PD), Blood",
    "Cervical Swab, MCS",
    "High Vaginal Swab (HVS), MCS",
    "Glycated Hemoglobin (HBA1c)",
    "Gram Stain – Ear Swab",
    "Haemoglobin [Hb]",
    "Haemolytic Screen (Haptoglobulin, Bilirubin T/D, LDH, FBC & Retic Count)",
    "Haptoglobin, Serum",
    "Hb Electrophoresis",
    "Helicobacter Pylori Ab IgM",
    "Helicobacter Pylori Stool Ag",
    "Hepatis B Surface Antibody (HBSab)",
    "Hep B Surface Antigen",
    "Hepatitis A Profile [IgG + IgM]",
    "Immunohistochemistry – HER2hemistry",
    "HIV Rapid Test",
    "Human Chronic Gonadotrophin",
    "Iron Deficiency Anemia (IDA) Profile",
    "JAK2 V617f Mutation",
    "Liver Function Tests (LFTs)ubin T/D, ALP, AST AST, GGT, No LDH)",
    "Mantoux (PPD) Skin Test",
    "Microscopy, Culture & Sensitivity (Blood)",
    "Microscopy,Culture,Sensitivity (Bacterial)- Eye",
    "Oral Glucose Tolerance Test",
    "Pap Smear Test for Cervical Cancer Screening",
    "HIV Viral Load (PCR)",
    "Protein Electrophoresis, Serum",
    "Prothrombin Time Index (PTI / INR)",
    "Reticulocyte Haemoglobin",
    "Reticulocytes Count [Measured and Corrected]",
    "Rh D Antigen",
    "Rheumatoid Arthritis Factor [analyser method]",
    "RPR [VDRL] – CSF",
    "RPR [VDRL], Serum",
    "Sex Hormone Binding Globulin (SHBG), Serum",
    "Sodium, Serum",
    "TB Culturecation On Culture",
    "TB PCR (Genexpert)",
    "Thyroid Stimulating Hormone (TSH), Serum",
    "Total Protein, Serum",
    "TSH & Thyroxine Levels",
    "TSH Cord Blood",
    "Urea/ Electrolytes/ Creatinine (UECs) /Kidney Function Test",
    "Widal’s Test for Typhoid",
    "Ziehl-Neelsen Stain for TB",
    "Chlamydia (NAAT) (PCR) Test",
    "Chlamydia IFA Test",
    "Chlamydia Rapid Diagnostic Test",
    "Lipid Profile",
    "CA 19-9 Test",
    "CA-125 Test",
    "CA 15-3 Test",
    "Drugs of Abuse Test -10 Panel Urine Test",
    "DNA Paternity Test",
    "Thyroid Function Tests (TFTs)",
    "Thyroxine, T4 (Serum)",
    "Free T3 Test, Serum",
    "Oraquick Home HIV Test Kit",
    "Leutenizing Hormone (LH), Serum",
    "Progesterone Test, Serum",
    "Follicle-Stimulating Hormone (FSH), Serum",
    "Testosterone Level Test",
    "Estrogen Level Test, Serum",
    "Anti-Mullerian Hormone (AMH) Test",
    "Semen Analysis Test (Seminalysis) for Male Infertility"	,
    "Fecal Occult Blood Test (FOBT)",
    "Urine Analysis Test -(Urinalysis) Biochemistry & Microscopy",
    "Prostatic Specific Antigen (PSA) Test",
    "Urine Albumin-Creatinine Ratio Test",
    "Chlamydia ELISA Test"
]